In [4]:
import requests
import pandas as pd

api_key = "e090bb15473dcdd368c80d400bc45780"

fred_series = {
    "new_orders": "A35SNO",
    "inventories": "A34HTI",
    "semiconductor_ppi": "PCU334413334413A"
}

new_orders: 413 rows
inventories: 414 rows
semiconductor_ppi: 602 rows

In [ ]:
dataframes = {}

for name, series_id in fred_series.items():

    url = "https://api.stlouisfed.org/fred/series/observations"

    params = {
        "api_key": api_key,
        "series_id": series_id,
        "file_type": "json"
    }

    response = requests.get(url, params=params)

    response.raise_for_status()

    data = response.json()

    df = pd.DataFrame(data["observations"])


    dataframes[name] = df

    print(f"{name}: {len(df)} rows"

In [14]:
def read_fred_data(series_id):
    params = {
        "api_key": api_key,
        "series_id": series_id,
        "file_type": "json"
    }
    response = requests.get(url, params=params)

    response.raise_for_status()

    data = response.json()

    df = pd.DataFrame(data["observations"])
    return df.head()

In [15]:
read_fred_data("PCU334413334413A")

  realtime_start realtime_end        date  value
0     2026-08-13   2026-08-13  1976-06-01  116.5
1     2026-08-13   2026-08-13  1976-07-01  116.0
2     2026-08-13   2026-08-13  1976-08-01  116.0
3     2026-08-13   2026-08-13  1976-09-01  114.7
4     2026-08-13   2026-08-13  1976-10-01  114.7

In [5]:
dataframes["new_orders"].head()

  realtime_start realtime_end        date value
0     2026-08-05   2026-08-05  1992-02-01  6199
1     2026-08-05   2026-08-05  1992-03-01  6614
2     2026-08-05   2026-08-05  1992-04-01  6858
3     2026-08-05   2026-08-05  1992-05-01  6825
4     2026-08-05   2026-08-05  1992-06-01  6606

In [6]:
dataframes["inventories"].head()

  realtime_start realtime_end        date value
0     2026-08-04   2026-08-04  1992-01-01  7793
1     2026-08-04   2026-08-04  1992-02-01  7714
2     2026-08-04   2026-08-04  1992-03-01  7661
3     2026-08-04   2026-08-04  1992-04-01  7520
4     2026-08-04   2026-08-04  1992-05-01  7427

In [7]:
dataframes["semiconductor_ppi"].head()

  realtime_start realtime_end        date  value
0     2026-08-13   2026-08-13  1976-06-01  116.5
1     2026-08-13   2026-08-13  1976-07-01  116.0
2     2026-08-13   2026-08-13  1976-08-01  116.0
3     2026-08-13   2026-08-13  1976-09-01  114.7
4     2026-08-13   2026-08-13  1976-10-01  114.7